name: CI
on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: self-hosted

    strategy:
        matrix:
            node-version: [18.x]

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
              node-version: ${{ matrix.node-version }}
        - run: cd server && npm install
        - run: cd frontend && npm install --legacy-peer-deps && npm run build
        - run: cp frontend/build server/site
        - run: npm start
